apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ibmday2021demo-deployment
spec:
  selector:
    matchLabels:
      app: day2021demo
  replicas: 2 
  template:
    metadata:
      labels:
        app: day2021demo
    spec:
      containers:
      - name: nginx
        image: ghcr.io/keisz/ibmday2021demo:latest
        ports:
        - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: ibmday2021demo-svc
spec:
  type: ClusterIP
  selector:
    app: day2021demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: day2021demo-route
spec:
  host: >-
    day2021demo.mycluster-satellite-8a7a030b7c73cc6a1bade95cb273562f-0000.upi.containers.appdomain.cloud
  to:
    kind: Service
    name: ibmday2021demo-svc
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None