apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ibmday2021demo-deployment
spec:
  selector:
    matchLabels:
      app: day2021demo
  replicas: 2 
  template:
    metadata:
      labels:
        app: day2021demo
    spec:
      containers:
      - name: nginx
        image: ghcr.io/keisz/ibmday2021demo:latest
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: ibmday2021demo-svc
spec:
  type: ClusterIP
  selector:
    app: day2021demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80